yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'),


]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200,)
    slug = models.SlugField(unique=True, verbose_name='URL')
    description = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='group_posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )

    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='Пост',
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='comments'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.text


class Follow (models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Подписчик',
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='following',
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(
                fields=["user", "author"], name="unique_follow"
            )
        ]

    def __str__(self):
        return f'{self.user} подписался на {self.author}'

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post
from .utils import split_page_to_page_pagination

User = get_user_model()


def index(request):
    """Формирует домашнюю страницу."""
    template = 'posts/index.html'
    posts = (
        Post.objects.select_related('author', 'group')
    )
    page_obj = split_page_to_page_pagination(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    """Формирует страницу с постами группы."""
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.group_posts.select_related('author', 'group')
    page_obj = split_page_to_page_pagination(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }

    return render(request, template, context)


def profile(request, username):
    """Формирует страницу профиля."""
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('author', 'group')
    page_obj = split_page_to_page_pagination(request, posts)
    following = (request.user.is_authenticated
                 and author.following.filter(user=request.user).exists())
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following
    }
    return render(request, template, context)


def post_detail(request, post_id):
    """Формирует страницу поста."""
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments = post.comments.select_related('post', 'author')
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    """Формирует страницу создания поста."""
    form = PostForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'posts/create.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', request.user.username)


@login_required
def post_edit(request, post_id):
    """Формирует страницу редактирования поста."""
    post = get_object_or_404(Post, pk=post_id)
    template = 'posts/create.html'
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post.id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post.id)
    context = {
        'post': post,
        'is_edit': True,
        'form': form
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(
        author__following__user=request.user)
    page_obj = split_page_to_page_pagination(request, posts)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', author)


@login_required
def profile_unfollow(request, username):
    user_follower = get_object_or_404(
        Follow,
        user=request.user,
        author__username=username
    )
    user_follower.delete()
    return redirect('posts:profile', username)

yatube/templates/includes/comment.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        {% include "includes/form_fields.html" %}
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text|linebreaksbr }}
      </p>
    </div>
  </div>
{% endfor %}

yatube/templates/includes/field_errors.html
{% load user_filters %}
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/form_fields.html
{% load user_filters %}
{% for field in form %}
  <div class="form-group row my-3">
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
        {% if field.field.required %}
          <span class="required text-danger">*</span>
        {% endif %}
    </label>
    {{ field|addclass:'form-control' }}
    {% if field.help_text %}
      <small
        id="{{ field.id_for_label }}-help"
        class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
{% endfor %}

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
  <header>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src="{% static 'img/logo.png' %}"
            width="30" height="30"
            class="d-inline-block align-top" alt="">
          <span style="color:red">Ya</span>tube
        </a>
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link{% if view_name  == 'about:author' %}active{% endif %}"
              href="{% url 'about:author' %}">Об авторе</a>
          </li>
          <li class="nav-item">
            <a class="nav-link{% if view_name  == 'about:tech' %}active{% endif %}"
              href="{% url 'about:tech' %}">Технологии</a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link{% if view_name  == 'posts:post_create' %}active{% endif %}"
                href="{% url 'posts:post_create' %}">Новая запись</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light
                {% if view_name  == 'users:password_reset' %}active{% endif %}"
                href="{% url 'users:password_reset' %}">Изменить пароль</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light
                {% if view_name  == 'users:logout' %}active{% endif %}"
                href="{% url 'users:logout' %}">Выйти</a>
            </li>
            <li>
              Пользователь: {{ user.username }}
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link link-light
                {% if view_name  == 'users:login' %}active{% endif %}"
                href="{% url 'users:login' %}">Войти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light
                {% if view_name  == 'users:signup' %}active{% endif %}"
                href="{% url 'users:signup' %}">Регистрация</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
{% endwith %}

yatube/templates/includes/image.html
{% load thumbnail %}
{% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img my-2" src="{{ im.url }}">
{% endthumbnail %}

yatube/templates/includes/post.html
<article>
  <ul>
    {% if author %}
      <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url "posts:profile" post.author.username %} ">
          все посты пользователя
        </a>
      </li>
    {% endif %}
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% include 'includes/image.html' %}
  <p>{{ post.text|linebreaksbr }}</p>
    <a href="{% url "posts:post_detail" post.id %}">подробная информация</a><br>
  {% if group_link and post.group %}
    <a href="{% url "posts:group_list" post.group.slug %}">все записи группы</a>
  {% endif %}
</article>