yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'),


]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200,)
    slug = models.SlugField(unique=True, verbose_name='URL')
    description = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='group_posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )

    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='Пост',
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='comments'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.text


class Follow (models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Подписчик',
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='following',
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(
                fields=["user", "author"], name="unique_follow"
            )
        ]

    def __str__(self):
        return f'{self.user} подписался на {self.author}'

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post
from .utils import split_page_to_page_pagination

User = get_user_model()


def index(request):
    """Формирует домашнюю страницу."""
    template = 'posts/index.html'
    posts = (
        Post.objects.select_related('author', 'group')
    )
    page_obj = split_page_to_page_pagination(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    """Формирует страницу с постами группы."""
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.group_posts.select_related('author', 'group')
    page_obj = split_page_to_page_pagination(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }

    return render(request, template, context)


def profile(request, username):
    """Формирует страницу профиля."""
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('author', 'group')
    page_obj = split_page_to_page_pagination(request, posts)
    following = (request.user.is_authenticated
                 and author.following.filter(user=request.user).exists())
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following
    }
    return render(request, template, context)


def post_detail(request, post_id):
    """Формирует страницу поста."""
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments = post.comments.select_related('post', 'author')
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    """Формирует страницу создания поста."""
    form = PostForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'posts/create.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', request.user.username)


@login_required
def post_edit(request, post_id):
    """Формирует страницу редактирования поста."""
    post = get_object_or_404(Post, pk=post_id)
    template = 'posts/create.html'
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post.id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post.id)
    context = {
        'post': post,
        'is_edit': True,
        'form': form
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(
        author__following__user=request.user)
    page_obj = split_page_to_page_pagination(request, posts)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', author)


@login_required
def profile_unfollow(request, username):
    user_follower = get_object_or_404(
        Follow,
        user=request.user,
        author__username=username
    )
    user_follower.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  {% load user_filters%}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать пост
            {% else %}
              Новый пост
            {% endif %}
          </div>
          <div class="card-body">
            {% include "includes/field_errors.html" %}
            <form method="post" enctype="multipart/form-data"
              {% if is_edit %}
                action="{% url 'posts:post_edit' post.id %}"
              {% else %}
                action="{% url 'posts:post_create' %}"
              {% endif %}
            >
            {% csrf_token %}
            {% include "includes/form_fields.html" %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %} Сохранить {% else %} Добавить {% endif %}
              </button>
            </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  <div class="container py-5">
    {% include 'posts/includes/switcher.html' %}
    <h1>Последние обновления на сайте</h1>
    {% for post in page_obj %}
      {% include "includes/post.html" with group_link=True author=True %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}
  Записи сообщестрва {{ group.title }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
      {% include "includes/post.html" with author=True %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  <div class="container py-5">
    {% include 'posts/includes/switcher.html' %}
    <h1>Последние обновления на сайте</h1>
    {% load cache %}
    {% cache 20 index_page %}
      {% for post in page_obj %}
        {% include "includes/post.html" with group_link=True author=True %}
        {% if not forloop.last %}
          <hr>
        {% endif %}
      {% endfor %}
    {% endcache %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
  Пост {{ post|truncatechars:30 }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group.title }}
              <a href="{% url "posts:group_list" post.group.slug %}">все записи группы</a>
            </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span> {{ post.author.posts.count }} </span>
          </li>
          <li class="list-group-item">
            <a href="{% url "posts:profile" post.author.username %} ">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
    <article class="col-12 col-md-9">
      <p>
        {% include 'includes/image.html' %}
        {{ post.text|linebreaksbr }}
      </p>
    </article>
    {% if user == post.author %}
      <a class="btn btn-primary" href="{% url "posts:post_edit" post.id %}">
        редактировать запись
      </a>
    {% endif %}
    {% include 'includes/comment.html' %}
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="mb-5">
      <h1>Все посты пользователя {{ author.get_full_name }}</h1>
      <h3>Всего постов: {{ page_obj.paginator.count }}</h3>
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
       {% endif %}
    </div>
    {% for post in page_obj %}
      {% include "includes/post.html" with group_link=True author=False %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}